### ISSUE TITLE
Change font colour to a darker grey shade (Header bar)

### ISSUE THREAD

**Issue by rajiniw95** [SciFlow-FYP/SciFlow-FYP.github.io#11]
#808080
#585858
#606060
#484848

check these colors

**Comment by kalpanibhagya** [comment]
changed to blue. 
![image](https://user-images.githubusercontent.com/23649993/71814870-c15b2580-30a3-11ea-9fda-17e7337b23ca.png)
![image](https://user-images.githubusercontent.com/23649993/71814893-d0da6e80-30a3-11ea-9615-3a6570dbd624.png)
