### ISSUE TITLE
Member image missing

### ISSUE THREAD

**Issue by amandaw95** [SciFlow-FYP/SciFlow-FYP.github.io#51]
![Untitled](https://user-images.githubusercontent.com/25957089/72042077-5a23b800-32d3-11ea-8922-e327860a31d8.png)
@kalpanibhagya

**Comment by kalpanibhagya** [comment]
![Screenshot from 2020-01-09 21-57-00](https://user-images.githubusercontent.com/23649993/72085259-05139080-332b-11ea-8fb5-42c08d183b72.png)

Website takes some time to load images.
